### ISSUE TITLE
使用vite安装会报错

### ISSUE THREAD

**Issue by TingYinHelen** [dotbitHQ/dotbit.js#43]
<img width="935" alt="image" src="https://user-images.githubusercontent.com/14006826/220806390-c78d89d7-5876-49ca-803f-4f3cbae0083a.png">
看上去是crypto-addr-codec的问题

**Comment by gengbingbing** [comment]
我也遇到了相同的问题

**Comment by web3max** [comment]
> 我也遇到了相同的问题

We plan to release a new version tomorrow that will fix this issue.
